version: '3.7'
services:
  pitter_sync:
    build: .
    env_file:
      - local.env
    depends_on:
      - redis
      - postgresql
    ports:
      - 8000:8000
  redis:
    image: redis
    command: redis-server --appendonly yes
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pitter_sync_postgresql:/var/lib/postgresql

volumes:
  pitter_sync_postgresql:
