version: '3.7'
services:
  pitter_async:
    build: ../backend-2019-trainee-async
    env_file:
      - ../backend-2019-trainee-async/local.env
  pitter_sync:
    build: .
    env_file:
      - local.env
    depends_on:
      - pitter_async
      - postgresql
    ports:
      - 8000:8000
    volumes:
      - /var/www/pitter/audio:/var/www/audio
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pitter_sync_postgresql:/var/lib/postgresql

volumes:
  pitter_sync_postgresql:
