version: '3.7'
services:
  pitter_sync:
    build: .
    env_file:
      - local.env
    depends_on:
      - redis
      - postgresql
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pitter_sync_postgresql:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  pitter_sync_postgresql:
