version: '3.7'
services:
  pitter_async:
    build: ../backend-2019-trainee-async
    env_file:
      - ../backend-2019-trainee-async/local.env
    depends_on:
      - redis
      - postgresql
    ports:
      - 8118:8118
  pitter_sync:
    build: .
    env_file:
      - local.env
    depends_on:
      - pitter_async
      - redis
      - postgresql
    ports:
      - 8000:8000
  redis:
    image: redis
    command: redis-server --appendonly yes
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pitter_sync_postgresql:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  pitter_sync_postgresql:
